import { ArrowRight, BookOpenCheck, SearchX } from "lucide-react";
import Link from "next/link";
import { DashboardShell } from "@/components/dashboard/dashboard-shell";

const categories = ["all", "getting-started", "lesson-workflow", "resources", "planning", "account"] as const;
type HelpCategory = typeof categories[number];

const articles: Array<{ category: Exclude<HelpCategory, "all">; title: string; summary: string; steps: string[]; href: string; linkLabel: string }> = [
  { category: "getting-started", title: "Create and save a lesson plan", summary: "Move from curriculum inputs to a validated structured lesson.", steps: ["Open New Lesson Plan and review the starting defaults.", "Choose curriculum, grade, subject, lesson type, and topic.", "Generate, review every section, and use Save now if you do not want to wait for autosave."], href: "/lesson/create", linkLabel: "Create a lesson" },
  { category: "lesson-workflow", title: "Build a complete teaching pack", summary: "Create slides, an assessment, a worksheet, and a rubric from one lesson.", steps: ["Open My Lesson Plans and choose a saved lesson.", "Select Teaching Pack from the row menu or editor.", "Generate only the classroom artifacts you need; each builder saves independently."], href: "/lesson", linkLabel: "Choose a lesson" },
  { category: "lesson-workflow", title: "Use pedagogy tools without losing edits", summary: "Alignment checks and AI suggestions leave the teacher in control.", steps: ["Open Pedagogy Tools inside the lesson editor.", "Run deterministic checks separately from AI differentiation suggestions.", "Accept or reject each proposal. Use Undo after an accepted section change when needed."], href: "/lesson", linkLabel: "Open lesson library" },
  { category: "resources", title: "Upload DOCX and PDF references safely", summary: "Only bounded text from supported documents is available to generation tools.", steps: ["Open Resources or the reference control in lesson creation.", "Upload a DOCX or text-based PDF within the stated size limit.", "Inspect extracted text and warnings before using the resource in a lesson. Image-only PDFs are not OCR processed."], href: "/resources", linkLabel: "Manage resources" },
  { category: "resources", title: "Understand curriculum verification", summary: "Verified local facts are distinct from teacher input and AI suggestions.", steps: ["Use the Curriculum browser to inspect provenance.", "Apply a verified competency to the new-lesson flow.", "Treat alignment results as planning aids, not official curriculum certification."], href: "/curriculum", linkLabel: "Browse curriculum" },
  { category: "lesson-workflow", title: "Keep private teacher notes private", summary: "Private notes stay outside student-facing material by default.", steps: ["Add notes in the Private Teacher Notes editor section.", "Teaching mode hides them until you explicitly open the notes tray.", "DOCX and PDF export excludes them unless you select the one-export inclusion option."], href: "/lesson", linkLabel: "Open lesson library" },
  { category: "planning", title: "Plan a teaching week or month", summary: "Calendar entries and dashboard schedule use the same saved data.", steps: ["Open Calendar and choose week or month view.", "Create an entry and optionally link a lesson, assessment, or teaching pack.", "Use the date and filters in the URL when sharing or bookmarking a planning view."], href: "/calendar", linkLabel: "Open calendar" },
  { category: "planning", title: "Apply classroom context intentionally", summary: "Reusable context is sent only to relevant lesson and AI actions you choose.", steps: ["Save broad class context without names, diagnoses, or sensitive learner details.", "Apply it from the new-lesson form when relevant.", "Review the applied values before generation."], href: "/settings/classroom-context", linkLabel: "Classroom context" },
  { category: "account", title: "Update profile, export details, and defaults", summary: "Profile details and preferences have different roles.", steps: ["School & Profile controls header and Word-export identity details.", "Preferences controls starting curriculum, format, duration, and language for new lessons.", "Verified records and explicit URL choices override saved defaults."], href: "/settings/profile", linkLabel: "Open profile" },
  { category: "account", title: "Recover from save conflicts or expired sessions", summary: "The application never silently overwrites newer remote lesson data.", steps: ["For a conflict, compare the newer version before choosing Load newer version or Keep my version.", "For an expired session, sign in again; the intended destination is preserved.", "For a failed save, keep the tab open and use Retry save after connectivity returns."], href: "/lesson", linkLabel: "Open lessons" },
];

function first(value: string | string[] | undefined) { return Array.isArray(value) ? value[0] ?? "" : value ?? ""; }

export default async function HelpPage({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const params = await searchParams;
  const query = first(params.q).trim().slice(0, 100);
  const rawCategory = first(params.category);
  const category: HelpCategory = categories.includes(rawCategory as HelpCategory) ? rawCategory as HelpCategory : "all";
  const normalized = query.toLowerCase();
  const results = articles.filter((article) => (category === "all" || article.category === category) && (!normalized || `${article.title} ${article.summary} ${article.steps.join(" ")}`.toLowerCase().includes(normalized)));

  return <DashboardShell currentPath="/help"><div className="library-page help-page"><header className="library-page-header"><div><h1>Help Center</h1><p>Practical guidance for the lesson, teaching-pack, resource, planning, and account workflows available today.</p></div><Link className="library-secondary-action" href="/dashboard">Return to dashboard</Link></header><form action="/help" className="help-filter-bar" method="get"><label><span>Search help</span><input defaultValue={query} name="q" placeholder="e.g. private notes, autosave, PDF" type="search" /></label><label><span>Workflow</span><select defaultValue={category} name="category"><option value="all">All workflows</option><option value="getting-started">Getting started</option><option value="lesson-workflow">Lessons and teaching packs</option><option value="resources">Curriculum and resources</option><option value="planning">Planning and classroom context</option><option value="account">Account and recovery</option></select></label><button type="submit">Find guidance</button><Link href="/help">Clear</Link></form><section aria-labelledby="help-results-heading" className="help-results"><div className="resource-list-heading"><h2 id="help-results-heading">Workflow guides</h2><span>{results.length} guide{results.length === 1 ? "" : "s"}</span></div>{results.length ? <div className="help-article-list">{results.map((article) => <details key={article.title}><summary><span><strong>{article.title}</strong><small>{article.summary}</small></span><BookOpenCheck aria-hidden="true" /></summary><div><ol>{article.steps.map((step) => <li key={step}>{step}</li>)}</ol><Link href={article.href}>{article.linkLabel}<ArrowRight aria-hidden="true" /></Link></div></details>)}</div> : <div className="library-empty-state compact"><SearchX aria-hidden="true" /><h2>No guide matches</h2><p>Try a broader phrase or clear the workflow filter.</p><Link href="/help">Show all help guides</Link></div>}</section><aside className="help-scope-note"><strong>Need a route back into the product?</strong><span>Each guide links directly to the implemented workflow. This phase does not include a support-ticket or email campaign system.</span></aside></div></DashboardShell>;
}
